### ISSUE TITLE
New Design Language

### ISSUE THREAD

**Issue by CodeLikeCrazE** [Darth-Ness/WarpCore#15]
In my opinion, the current design language is kinda ugly, here is a concept for a new design language. I can implement it in code if you like it. the buttons are problably gonna be smaller in the final version.

![iMac - 1](https://user-images.githubusercontent.com/63984309/185533389-a46962e0-1fc6-426e-a1c4-dd30259d97ed.png)

**Comment by Darth-Ness** [comment]
Sorry for responding late. I didn't really like the monochromatic design, so I tweaked the current one. 
![2022-08-21_07-42](https://user-images.githubusercontent.com/75047141/185789228-e78332f8-071d-48fc-baae-e92c0c42e90b.png)
Is that better?

**Comment by CodeLikeCrazE** [comment]
Try adding more left and right padding on the tabs and search bar, and using feather icons. Also maybe use flex box to make all the tabs take up as much space as possible, and center the text.

**Comment by Darth-Ness** [comment]
> 

Are you wanting me to reopen this? Also isn't that the same thing you said above that comment?

**Comment by CodeLikeCrazE** [comment]
I dont know why that happened. Forever ago I tried to respond to this via email, and I guess only now it's registering my response. Do not reopen this.
