### ISSUE TITLE
Misc: Restructuring

### ISSUE THREAD

**Issue by CodeLikeCrazE** [Darth-Ness/WarpCore#22]
We should problably break the codebase up into 3 branches.

- stable (basically main, for finished stable versions that have a polished version of the features with no bugs)
- beta (for features that dont have bugs but arent fully polished)
- dev (the live development branch)

We should also problably set up github actions to automatically build a release.

**Comment by Darth-Ness** [comment]
Maybe everytime we push to stable it makes a stable release, and  beta release when push to the beta branch?

**Comment by CodeLikeCrazE** [comment]
Yep, that would be good. So we would push updates to dev, and if they are stable enough we move them to beta, then finally stable.

**Comment by Darth-Ness** [comment]
All right, there are now dev and beta branches. Both are currently up to date with the stable version.
Now I'll try to figure out how to set up the GitHub Actions thing.

**Comment by Darth-Ness** [comment]
Fixed as of #24
