### ISSUE TITLE
Misc: License?

### ISSUE THREAD

**Issue by CodeLikeCrazE** [Darth-Ness/WarpCore#30]
We should probably add a license and also a security policy. 
I think we should use GPLv3 as our license, and as for the security policy, just open an issue.

**Comment by Darth-Ness** [comment]
Why GPLv3 over MIT?

**Comment by CodeLikeCrazE** [comment]
GPL prevents closed source forks.

**Comment by Darth-Ness** [comment]
There, I added it to the dev branch.
